
CREATE TABLE `T_POM_R_DETAIL` (
  `DETAIL_SEQ` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '流水号',
  `SITE_ID` int(11) NOT NULL COMMENT '站点编号',
  `TITLE` varchar(1000) DEFAULT NULL COMMENT '标题',
  `URL` varchar(4000) DEFAULT NULL COMMENT 'URL',
  `CRAWL_TIME` datetime NOT NULL COMMENT '抓取时间',
  `IN_TIME` datetime DEFAULT NULL COMMENT '入库时间',
  `SOURCE` varchar(128) DEFAULT NULL COMMENT '来源',
  `AUTHOR` varchar(128) DEFAULT NULL COMMENT '作者',
  `EDITOR` varchar(128) DEFAULT NULL COMMENT '编辑',
  `PUBLISH_TIME` datetime NOT NULL COMMENT '发表时间',
  `URL_ENCODE` varchar(250) NOT NULL COMMENT 'URL编码',
  `TYPE_ID` int(11) DEFAULT NULL COMMENT '词条',
  `TEMPLATE_TYPE` varchar(32) DEFAULT NULL COMMENT '模板类型',
  PRIMARY KEY (`DETAIL_SEQ`),
  UNIQUE KEY `UNI_DETAIL_URL` (`URL_ENCODE`),
  KEY `IDX_CRAWL_TIME` (`CRAWL_TIME`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='舆情明细表';