INSERT INTO `T_CRAWL_M_SITE_TYPE` (`SITE_TYPE_ID`, `SITE_TYPE_NAME`, `IS_VALID`) VALUES (0, '新闻', '1');
INSERT INTO `T_CRAWL_M_SITE_TYPE` (`SITE_TYPE_ID`, `SITE_TYPE_NAME`, `IS_VALID`) VALUES (1, '媒体', '1');
INSERT INTO `T_CRAWL_M_SITE_TYPE` (`SITE_TYPE_ID`, `SITE_TYPE_NAME`, `IS_VALID`) VALUES (2, '政府', '1');
INSERT INTO `T_CRAWL_M_SITE_TYPE` (`SITE_TYPE_ID`, `SITE_TYPE_NAME`, `IS_VALID`) VALUES (3, '论坛', '1');
INSERT INTO `T_CRAWL_M_SITE_TYPE` (`SITE_TYPE_ID`, `SITE_TYPE_NAME`, `IS_VALID`) VALUES (4, '贴吧', '1');
INSERT INTO `T_CRAWL_M_SITE_TYPE` (`SITE_TYPE_ID`, `SITE_TYPE_NAME`, `IS_VALID`) VALUES (5, '博客', '1');
INSERT INTO `T_CRAWL_M_SITE_TYPE` (`SITE_TYPE_ID`, `SITE_TYPE_NAME`, `IS_VALID`) VALUES (6, '微博', '1');
INSERT INTO `T_CRAWL_M_SITE_TYPE` (`SITE_TYPE_ID`, `SITE_TYPE_NAME`, `IS_VALID`) VALUES (7, '其他', '1');
