INSERT INTO `T_M_COUNTRY` (`COUNTRY_CODE`, `COUNTRY_NAME`) VALUES (0, '中国');
INSERT INTO `T_M_COUNTRY` (`COUNTRY_CODE`, `COUNTRY_NAME`) VALUES (1, '美国');
INSERT INTO `T_M_COUNTRY` (`COUNTRY_CODE`, `COUNTRY_NAME`) VALUES (2, '英国');
